# Welcome to Jekyll!
#

# Site settings
title: Hung-Chung Kuo
description: |
  A Passionate Programmer
owner: Hung-Chung Kuo
first_published: 2017
email: johnhckuo@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://johnhckuo.github.io/" # the base hostname & protocol for your site
social:
  github: https://github.com/johnhckuo
  linkedin-square: https://www.linkedin.com/in/johnhckuo/
  facebook-official: https://facebook.com/johnhckuo
  google-plus-square: https://plus.google.com/u/0/+HungChungKuo
  email: johnhckuo@gmail.com

# Build settings
markdown: kramdown
#sass:
#  style: compressed
