# Welcome to Jekyll!
#

# Site settings
title: Hung-Chung Kuo
description: |
  A Passionate Programmer
owner: Hung-Chung Kuo
first_published: 2017
email: johnhckuo@gmail.com
google_analytics: UA-108369170-1
baseurl: "" # the subpath of your site, e.g. /blog
url: "johnhckuo.github.io" # the base hostname & protocol for your site
social:
  github: https://github.com/johnhckuo
  linkedin-square: https://www.linkedin.com/in/johnhckuo/
  facebook-official: https://facebook.com/johnhckuo
  google-plus-square: https://plus.google.com/u/0/+HungChungKuo
  email: johnhckuo@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:
    - '/'
  Blog:
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

# Build settings
markdown: kramdown
#sass:
#  style: compressed
